services:
  mysql:
    image: sv_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: study_vault
    ports:
      - "6609:3306"
    volumes:
      - mysql_data:/var/lib/mysql  # Data persistence for MySQL

  grpc_api:
    image: sv_grpc
    ports:
      - "50051:50051"  # gRPC API exposed on port 50052
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: my_database
    volumes:
      - sv_files:/data/files  # Attach volume to the gRPC API container

volumes:
  mysql_data:
    driver: local
  sv_files:
    driver: local
